/**
 * Test script to verify that dotenv is loading environment variables correctly
 * Run this with: node test-env.js
 */

console.log('Starting environment variable test...');

try {
  // Attempt to load dotenv
  const dotenv = require('dotenv');
  const result = dotenv.config();
  
  if (result.error) {
    console.error('Error loading .env file:', result.error);
  } else {
    console.log('Successfully loaded .env file');
    
    // Check for specific environment variables
    console.log('\nEnvironment Variables:');
    console.log('---------------------');
    
    // Check JWT_SECRET
    if (process.env.JWT_SECRET) {
      console.log('JWT_SECRET: ✅ Set');
      // Show first few characters for verification
      console.log(`  Value starts with: ${process.env.JWT_SECRET.substring(0, 3)}...`);
    } else {
      console.log('JWT_SECRET: ❌ Not set');
    }
    
    // Check ADMIN_PASSWORD
    if (process.env.ADMIN_PASSWORD) {
      console.log('ADMIN_PASSWORD: ✅ Set');
      // Show first few characters for verification
      console.log(`  Value starts with: ${process.env.ADMIN_PASSWORD.substring(0, 3)}...`);
    } else {
      console.log('ADMIN_PASSWORD: ❌ Not set');
    }
    
    // Check other common variables
    console.log('PORT:', process.env.PORT || '❌ Not set');
    console.log('NODE_ENV:', process.env.NODE_ENV || '❌ Not set');
    
    // Show all environment variables (excluding system ones)
    console.log('\nAll Environment Variables:');
    console.log('-------------------------');
    const envVars = Object.keys(process.env)
      .filter(key => !key.match(/^(PATH|APPDATA|TEMP|TMP|COMPUTERNAME|OS|SystemDrive|SystemRoot|USERPROFILE|HOMEPATH|PROCESSOR|windir|PROMPT|PATHEXT|LOGONSERVER|SESSIONNAME|ALLUSERSPROFILE|PUBLIC|LOCALAPPDATA|PROGRAMFILES|COMMONPROGRAMFILES|PROGRAMDATA|USERDOMAIN|HOMEDRIVE|COMSPEC|DRIVERDATA|PSMODULEPATH|ONEDRIVE|PROGRAMW6432|COMMONPROGRAMW6432|VSCODE|TERM|COLORTERM|LANG|SHELL|SHLVL|PWD|HOME|OLDPWD|_|INIT_CWD|npm_|TERM_PROGRAM|TERM_PROGRAM_VERSION|LANGUAGE|LSCOLORS|NVM_|ANDROID_|JAVA_|GRADLE_|HISTCONTROL|HISTSIZE|HISTFILESIZE|DISPLAY|SSH_|XDG_|WINDOWID|WAYLAND_|DESKTOP_|GDMSESSION|GNOME_|GTK|QT|DBUS_|XAUTHORITY|XMODIFIERS|XCURSOR_|XSESSION|IRBRC|GEM_|RUBY_|GOPATH|GOROOT|PYTHONPATH|PYTHONSTARTUP|PYTHONHOME|PYTHONIOENCODING|VIRTUAL_ENV|CONDA_|PIPENV_|POETRY_|RUSTUP_|CARGO_|DOTNET_|NUGET_|ASPNETCORE_|DOTNET_|JAVA_|MAVEN_|GRADLE_|ANDROID_|FLUTTER_|DART_|CHROME_|FIREFOX_|EDGE_|WEBKIT_|PUPPETEER_|SELENIUM_|CYPRESS_|JEST_|MOCHA_|KARMA_|BABEL_|WEBPACK_|ROLLUP_|PARCEL_|GULP_|GRUNT_|YARN_|NPM_|NODE_|TS_|TYPESCRIPT_|ESLINT_|PRETTIER_|STYLELINT_|POSTCSS_|SASS_|LESS_|TAILWIND_|BOOTSTRAP_|MATERIAL_|STORYBOOK_|NEXT_|GATSBY_|REACT_|VUE_|ANGULAR_|SVELTE_|EMBER_|BACKBONE_|JQUERY_|LODASH_|UNDERSCORE_|RAMDA_|RXJS_|REDUX_|MOBX_|VUEX_|NGRX_|APOLLO_|GRAPHQL_|PRISMA_|SEQUELIZE_|MONGOOSE_|TYPEORM_|KNEX_|OBJECTION_|BOOKSHELF_|WATERLINE_|PASSPORT_|JWT_|OAUTH_|AUTH0_|FIREBASE_|SUPABASE_|STRIPE_|PAYPAL_|BRAINTREE_|SQUARE_|SHOPIFY_|WOO_|MAGENTO_|CONTENTFUL_|SANITY_|STRAPI_|WORDPRESS_|DRUPAL_|JOOMLA_|GHOST_|NETLIFY_|VERCEL_|HEROKU_|AWS_|AZURE_|GCP_|DIGITALOCEAN_|LINODE_|VULTR_|CLOUDFLARE_|AKAMAI_|FASTLY_|SENTRY_|DATADOG_|NEWRELIC_|LOGGLY_|PAPERTRAIL_|SPLUNK_|ELASTICSEARCH_|KIBANA_|LOGSTASH_|PROMETHEUS_|GRAFANA_|INFLUXDB_|TELEGRAF_|REDIS_|MEMCACHED_|MONGODB_|POSTGRESQL_|MYSQL_|MARIADB_|SQLITE_|MSSQL_|ORACLE_|DB2_|CASSANDRA_|COUCHDB_|DYNAMODB_|COSMOSDB_|FIRESTORE_|ALGOLIA_|ELASTICSEARCH_|SOLR_|MEILISEARCH_|TYPESENSE_|OPENSEARCH_|KAFKA_|RABBITMQ_|ACTIVEMQ_|NATS_|ZEROMQ_|MQTT_|AMQP_|SQS_|SNS_|KINESIS_|PUBSUB_|EVENTHUB_|SERVICEBUS_|DOCKER_|KUBERNETES_|HELM_|ISTIO_|LINKERD_|CONSUL_|VAULT_|TERRAFORM_|ANSIBLE_|PUPPET_|CHEF_|SALT_|PACKER_|VAGRANT_|VIRTUALBOX_|VMWARE_|HYPER_|KVM_|XEN_|QEMU_|LXC_|LXD_|PODMAN_|BUILDAH_|SKOPEO_|CONTAINERD_|CRI_|OCI_|OPENSHIFT_|RANCHER_|MINIKUBE_|KIND_|K3S_|K3D_|MICROK8S_|EKS_|AKS_|GKE_|DIGITALOCEAN_|LINODE_|VULTR_|HETZNER_|OVH_|SCALEWAY_|UPCLOUD_|EXOSCALE_|CLOUDSCALE_|PACKET_|EQUINIX_|IBM_|ORACLE_|ALIBABA_|TENCENT_|HUAWEI_|YANDEX_|MAIL_|SENDGRID_|MAILGUN_|POSTMARK_|SES_|MAILCHIMP_|CONVERTKIT_|DRIP_|KLAVIYO_|TWILIO_|NEXMO_|MESSAGEBIRD_|PLIVO_|BANDWIDTH_|VONAGE_|SINCH_|TELNYX_|CLICKSEND_|TEXTMAGIC_|CLOCKWORK_|INFOBIP_|KALEYRA_|VIBER_|WHATSAPP_|TELEGRAM_|DISCORD_|SLACK_|TEAMS_|ZOOM_|MEET_|WEBEX_|GOTOMEETING_|BLUEJEANS_|WHEREBY_|DAILY_|AGORA_|TOKBOX_|TWITCH_|YOUTUBE_|VIMEO_|WISTIA_|BRIGHTCOVE_|JWPLAYER_|VIDEOJS_|HLS_|DASH_|RTMP_|RTSP_|SRT_|WEBRTC_|FFMPEG_|GSTREAMER_|OPENCV_|TENSORFLOW_|PYTORCH_|KERAS_|SCIKIT_|NUMPY_|PANDAS_|SCIPY_|MATPLOTLIB_|SEABORN_|PLOTLY_|BOKEH_|D3_|CHARTJS_|HIGHCHARTS_|ECHARTS_|APEXCHARTS_|RECHARTS_|NIVO_|VISX_|VICTORY_|VEGA_|LEAFLET_|MAPBOX_|OPENLAYERS_|CESIUM_|THREEJS_|BABYLONJS_|UNITY_|UNREAL_|GODOT_|PHASER_|PIXI_|COCOS_|PLAYCANVAS_|AFRAME_|WEBGL_|WEBGPU_|CANVAS_|SVG_|GSAP_|ANIME_|VELOCITY_|POPMOTION_|FRAMER_|MOTION_|LOTTIE_|RIVE_|SPLINE_)/i))
      .sort();
    
    envVars.forEach(key => {
      const value = process.env[key];
      // Hide sensitive values
      if (key.includes('SECRET') || key.includes('PASSWORD') || key.includes('KEY')) {
        console.log(`${key}: [Hidden for security]`);
      } else {
        console.log(`${key}: ${value}`);
      }
    });
  }
} catch (error) {
  console.error('Failed to load dotenv:', error);
}

console.log('\nTest complete.'); 